In [542]:
import numpy as np
import pandas as pd
import pickle

In [543]:
df = pd.read_excel('final-data.xlsx')
print(df.head())

   Year Team          Event    GDP  Population  Host country  \
0  1992  aus  Weightlifting  18570    17402173             0   
1  1992  aus         hockey  18570    17402173             0   
2  1992  aus     basketball  18570    17402173             0   
3  1992  aus        cycling  18570    17402173             0   
4  1992  aus       football  18570    17402173             0   

   Unemployment Rate (%)  Human development index(HDI)  Life expectancy  \
0                  10.73                          0.87         77.37805   
1                  10.73                          0.87         77.37805   
2                  10.73                          0.87         77.37805   
3                  10.73                          0.87         77.37805   
4                  10.73                          0.87         77.37805   

   Calories from animal protein (FAO (2017))  \
0                                     283.56   
1                                     283.56   
2                   

In [544]:
# df.isna().sum()

In [545]:
def normalize(x):
    x_min = np.min(x)
    x_max = np.max(x)
    x -= x_min
    x /= (x_max-x_min)
    return x

In [546]:
def sigmoid(x):
    sig = 1 / (1 + np.exp(-x))
    return sig

In [547]:
event = 'swimming'
df = df.loc[df.Event == event]
# print(df.head(5))

In [548]:
train = df.loc[df.Year <= 2008]
test = df.loc[df.Year > 2008]


In [549]:
x_train = train.drop('GOLD',axis=1)
x_train = x_train.drop('SILVER',axis=1)
x_train = x_train.drop('BRONZE',axis=1)
x_train = x_train.drop('Year',axis=1)
x_train = x_train.drop('Team',axis=1)
x_train = x_train.drop('Event',axis=1)
# print(x_train)

In [550]:
train_gold = train['GOLD']
train_silver = train['SILVER']
train_bronze = train['BRONZE']
# y_train = pd.concat([train_gold,train_silver,train_bronze],axis=1)
y_train = 5*train_gold + 3*train_silver + train_bronze
# print(y_train)

In [551]:
x_test = test.drop('GOLD',axis=1)
x_test = x_test.drop('SILVER',axis=1)
x_test = x_test.drop('BRONZE',axis=1)
x_test = x_test.drop('Year',axis=1)
x_test = x_test.drop('Team',axis=1)
x_test = x_test.drop('Event',axis=1)
# print(x_test)

In [552]:
test_gold = test['GOLD']
test_silver = test['SILVER']
test_bronze = test['BRONZE']
# y_test = pd.concat([test_gold,test_silver,test_bronze],axis=1)
y_test = 5*test_gold + 3*test_silver + test_bronze
# print(y_test)

In [553]:
X_train = np.array(x_train)
X_test = np.array(x_test)
Y_train = np.array(y_train)
Y_test = np.array(y_test)
print(Y_test)
print(X_test)

[0 0 5 0 0 0 1 0 1]
[[6.80120000e+04 2.29039480e+07 0.00000000e+00 5.22000000e+00
  9.40000000e-01 8.20463400e+01 2.81160000e+02 1.36880000e+02
  1.37133000e+03 1.46763000e+03 1.00000000e+00 8.90000000e+01]
 [5.26690000e+04 3.49220300e+07 0.00000000e+00 7.40000000e+00
  9.10000000e-01 8.16487800e+01 2.21640000e+02 1.96760000e+02
  1.34109000e+03 1.72551000e+03 1.00000000e+00 6.00000000e+01]
 [6.31700000e+03 1.38420640e+09 0.00000000e+00 1.02800000e+01
  7.20000000e-01 7.50130000e+01 1.56840000e+02 2.32680000e+02
  8.59770000e+02 1.84871000e+03 0.00000000e+00 8.10000000e+01]
 [4.08720000e+04 6.35642210e+07 0.00000000e+00 9.40000000e+00
  8.90000000e-01 8.19682900e+01 2.79120000e+02 1.65880000e+02
  1.41948000e+03 1.59552000e+03 1.00000000e+00 5.40000000e+01]
 [1.44400000e+03 1.26578025e+09 0.00000000e+00 5.66000000e+00
  6.00000000e-01 6.75450000e+01 4.88000000e+01 1.87920000e+02
  4.73670000e+02 1.72461000e+03 1.00000000e+00 1.00000000e+00]
 [3.50520000e+04 5.98794710e+07 0.00000000e+0

In [554]:
# from sklearn.linear_model import LogisticRegression
# model = LogisticRegression(multi_class='multinomial',solver='lbfgs')

In [555]:
from sklearn.svm import LinearSVC
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

model = make_pipeline(StandardScaler(),
                    LinearSVC(random_state=0, tol=1e-5))

In [556]:
model.fit(X_train,Y_train)
#filename = event+'.sav'
#pickle.dump(model, open(filename, 'wb'))


 

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('linearsvc', LinearSVC(random_state=0, tol=1e-05))])

In [557]:
model.predict([[68310,331449281,0,8.31,0.926,77.3,279.04,159.68,1460.07,1788.21,1,96]])
print(model.predict(X_test))
print(Y_test)

[0 0 0 0 0 0 0 0 6]
[0 0 5 0 0 0 1 0 1]


In [558]:
model.score(X_test,Y_test)

0.6666666666666666

In [559]:
X_test.shape

(9, 12)